name: Development test

on:
  push:
    branches:
      - development  # Trigger when a release is published

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the required Node.js version

    # - name: Install dependencies
    #   run: npm install

    # - name: Build React app
    #   run: npm run build

    - name: Debug Secrets
      run: |
        if [ -z "${{ secrets.AWS_ACCESS_KEY_ID }}" ]; then
          echo "AWS_ACCESS_KEY_ID is not set!"
          exit 1
        else
          echo "AWS_ACCESS_KEY_ID is set."
        fi

        if [ -z "${{ secrets.AWS_SECRET_ACCESS_KEY }}" ]; then
          echo "AWS_SECRET_ACCESS_KEY is not set!"
          exit 1
        else
          echo "AWS_SECRET_ACCESS_KEY is set."
        fi


    - name: Configure AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Sync S3 bucket
      run: aws s3 sync ./ s3://devtest-new --acl public-read --delete

    - name: Output Release Information
      run: echo "Deployed   Release:"
