name: Deploy React to S3 on Specific Release

on:
  release:
    types: 
      - published  # Trigger when a release is published

jobs:
  deploy:
    if: startsWith(github.event.release.tag_name, 'v1.')  # Only deploy for releases with tags that start with 'v1.'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the required Node.js version

    - name: Install dependencies
      run: npm install

    - name: Build React app
      run: npm run build

    - name: Configure AWS credentials
      run: |
        mkdir -p ~/.aws
        echo "[default]" > ~/.aws/credentials
        echo "aws_access_key_id = ${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
        echo "aws_secret_access_key = ${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
        echo "[default]" > ~/.aws/config
        echo "region = ${{ secrets.AWS_REGION }}" >> ~/.aws/config

    - name: Install AWS CLI
      run: sudo apt-get install -y awscli

    - name: Sync S3 bucket
      run: aws s3 sync ./build s3://${{ secrets.AWS_S3_BUCKET }} --acl public-read --delete

    - name: Output Release Information
      run: echo "Deployed Release:"
